#!/usr/bin/env bash
# hmdm-stats installer — idempotent, safe to re-run after changing .env.
#
#   sudo ./install.sh [--skip-grafana-install] [--skip-webpanel] [--dry-run]
#
# Flow: preflight (live schema discovery) -> /etc/hmdm-stats/hmdm-stats.conf ->
# migration -> DB roles -> cron + logging -> one foreground snapshot (aborts on
# failure) -> Grafana install/provisioning -> optional web panel Analytics tab.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
RUNTIME=/opt/hmdm-stats
ETC=/etc/hmdm-stats
CONF="$ETC/hmdm-stats.conf"
LOG_DIR=/var/log/hmdm-stats
GRAFANA_DASH_DIR=/var/lib/grafana/dashboards/hmdm-stats

SKIP_GRAFANA_INSTALL=0
SKIP_WEBPANEL=0
DRY_RUN=0
for arg in "$@"; do
    case "$arg" in
        --skip-grafana-install) SKIP_GRAFANA_INSTALL=1 ;;
        --skip-webpanel)        SKIP_WEBPANEL=1 ;;
        --dry-run)              DRY_RUN=1 ;;
        *) echo "unknown flag: $arg" >&2; exit 1 ;;
    esac
done

say()  { printf '\n== %s ==\n' "$*"; }
run()  { if [ "$DRY_RUN" -eq 1 ]; then echo "DRY: $*"; else "$@"; fi; }

[ "$(id -u)" -eq 0 ] || { echo "run as root: sudo ./install.sh" >&2; exit 1; }

# --- 0. .env -------------------------------------------------------------------
if [ ! -f "$HERE/.env" ]; then
    cp -n "$HERE/.env.example" "$HERE/.env"
    chmod 600 "$HERE/.env"
    echo "Created $HERE/.env from the example. Review it (alert routing, SMTP," >&2
    echo "bind address), then re-run: sudo ./install.sh" >&2
    exit 1
fi
chmod 600 "$HERE/.env"
set -a; . "$HERE/.env"; set +a

# defaults for anything left empty in .env
SNAPSHOT_INTERVAL_MIN=${SNAPSHOT_INTERVAL_MIN:-10}
ONLINE_THRESHOLD_SECONDS=${ONLINE_THRESHOLD_SECONDS:-1800}
RETENTION_DAYS=${RETENTION_DAYS:-30}
BATTERY_WARN=${BATTERY_WARN:-20}
BATTERY_CRIT=${BATTERY_CRIT:-5}
OFFLINE_ALERT_SECONDS=${OFFLINE_ALERT_SECONDS:-3600}
HMDM_DB_NAME=${HMDM_DB_NAME:-hmdm}
GRAFANA_BIND_ADDR=${GRAFANA_BIND_ADDR:-10.10.10.12}
GRAFANA_URL=${GRAFANA_URL:-http://$GRAFANA_BIND_ADDR:3000}
case "$SNAPSHOT_INTERVAL_MIN" in
    ''|*[!0-9]*) echo "SNAPSHOT_INTERVAL_MIN must be a number" >&2; exit 1 ;;
esac
BUCKET_SECONDS=$((SNAPSHOT_INTERVAL_MIN * 60))

# --- 1. preflight -----------------------------------------------------------------
say "preflight"
HMDM_DB_NAME="$HMDM_DB_NAME" BATTERY_JSON_KEY="${BATTERY_JSON_KEY:-batteryLevel}" \
CHARGING_JSON_KEY="${CHARGING_JSON_KEY:-batteryCharging}" \
    bash "$HERE/preflight.sh" "$HMDM_DB_NAME"
PF="$HERE/preflight.out"
[ -f "$PF" ] || { echo "preflight.out missing" >&2; exit 1; }
pf_get() { sed -n "s/^$1 = //p" "$PF" | head -1; }
AUTH_MODE=$(pf_get auth_mode)

[ "$DRY_RUN" -eq 1 ] && { echo "DRY RUN: preflight passed, stopping before any changes."; exit 0; }

# --- 2. passwords (generate once, persist in the conf) ------------------------------
existing_conf_get() { [ -f "$CONF" ] && sed -n "s/^# $1=//p" "$CONF" | head -1 || true; }
HMDM_STATS_DB_PASSWORD=${HMDM_STATS_DB_PASSWORD:-$(existing_conf_get hmdm_stats_password)}
HMDM_GRAFANA_RO_PASSWORD=${HMDM_GRAFANA_RO_PASSWORD:-$(existing_conf_get grafana_ro_password)}
[ -n "$HMDM_STATS_DB_PASSWORD" ] || HMDM_STATS_DB_PASSWORD=$(openssl rand -hex 16)
[ -n "$HMDM_GRAFANA_RO_PASSWORD" ] || HMDM_GRAFANA_RO_PASSWORD=$(openssl rand -hex 16)
export HMDM_STATS_DB_PASSWORD HMDM_GRAFANA_RO_PASSWORD HMDM_DB_NAME GRAFANA_BIND_ADDR

# --- 3. runtime copy -----------------------------------------------------------------
say "runtime files -> $RUNTIME"
if [ "$HERE" != "$RUNTIME" ]; then
    mkdir -p "$RUNTIME"
    cp -a "$HERE/." "$RUNTIME/"
fi
chmod 755 "$RUNTIME"/preflight.sh "$RUNTIME"/install.sh \
          "$RUNTIME"/snapshot/snapshot-cron.sh "$RUNTIME"/webpanel/inject-analytics-tab.sh

# --- 4. /etc/hmdm-stats/hmdm-stats.conf -----------------------------------------------
say "write $CONF"
mkdir -p "$ETC"
if [ "$AUTH_MODE" = "password" ]; then
    DSN="host=127.0.0.1 port=5432 dbname=$HMDM_DB_NAME user=hmdm_stats password=$HMDM_STATS_DB_PASSWORD"
    CRON_USER=root
else
    DSN="dbname=$HMDM_DB_NAME"
    CRON_USER=postgres
fi
{
    echo "# generated by install.sh $(date -Is) — re-run install.sh to regenerate"
    echo "# hmdm_stats_password=$HMDM_STATS_DB_PASSWORD"
    echo "# grafana_ro_password=$HMDM_GRAFANA_RO_PASSWORD"
    echo "[db]"
    echo "dsn = $DSN"
    sed -n '/^\[mapping\]/,/^\[detected\]/p' "$PF" | sed '/^\[detected\]/d'
    echo "[sampling]"
    echo "bucket_seconds = $BUCKET_SECONDS"
    echo "online_threshold_seconds = $ONLINE_THRESHOLD_SECONDS"
    echo "retention_days = $RETENTION_DAYS"
} >"$CONF"
chmod 600 "$CONF"
[ "$CRON_USER" = "postgres" ] && chown postgres:postgres "$CONF"

# --- 5. migration + roles ---------------------------------------------------------------
say "database migration + roles"
sudo -u postgres psql -d "$HMDM_DB_NAME" -v ON_ERROR_STOP=1 -f "$RUNTIME/migrations/001_device_status_history.sql"
sudo -u postgres psql -d "$HMDM_DB_NAME" -v ON_ERROR_STOP=1 <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'hmdm_stats') THEN
        CREATE ROLE hmdm_stats LOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'grafana_ro') THEN
        CREATE ROLE grafana_ro LOGIN;
    END IF;
END
\$\$;
ALTER ROLE hmdm_stats PASSWORD '$HMDM_STATS_DB_PASSWORD';
ALTER ROLE grafana_ro PASSWORD '$HMDM_GRAFANA_RO_PASSWORD';
GRANT SELECT ON devices TO hmdm_stats;
GRANT SELECT, INSERT, DELETE ON device_status_history TO hmdm_stats;
GRANT SELECT ON device_status_history TO grafana_ro;
SQL

# --- 6. snapshot dependencies, logging, cron ----------------------------------------------
say "snapshot job"
if ! python3 -c 'import psycopg2' 2>/dev/null || ! command -v envsubst >/dev/null; then
    apt-get update -qq && apt-get install -y -qq python3-psycopg2 gettext-base
fi
mkdir -p "$LOG_DIR"
[ "$CRON_USER" = "postgres" ] && chown postgres:postgres "$LOG_DIR"
install -m 644 "$RUNTIME/config/logrotate-hmdm-stats" /etc/logrotate.d/hmdm-stats
sed -e "s/__INTERVAL__/$SNAPSHOT_INTERVAL_MIN/" -e "s/__CRON_USER__/$CRON_USER/" \
    "$RUNTIME/snapshot/hmdm-stats.cron" >/etc/cron.d/hmdm-stats
chmod 644 /etc/cron.d/hmdm-stats

say "first snapshot (foreground — proves the DB path)"
if [ "$CRON_USER" = "postgres" ]; then
    sudo -u postgres python3 "$RUNTIME/snapshot/snapshot.py" "$CONF"
else
    python3 "$RUNTIME/snapshot/snapshot.py" "$CONF"
fi
echo "first snapshot OK"

# --- 7. Grafana -------------------------------------------------------------------------------
say "grafana"
if [ "$SKIP_GRAFANA_INSTALL" -eq 0 ] && ! dpkg -s grafana >/dev/null 2>&1; then
    apt-get install -y -qq apt-transport-https software-properties-common wget gpg
    mkdir -p /etc/apt/keyrings
    [ -f /etc/apt/keyrings/grafana.gpg ] || \
        wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor >/etc/apt/keyrings/grafana.gpg
    echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" \
        >/etc/apt/sources.list.d/grafana.list
    apt-get update -qq
    apt-get install -y -qq grafana
fi
dpkg -s grafana >/dev/null 2>&1 || { echo "grafana not installed" >&2; exit 1; }

# merge overrides into grafana.ini (configparser, with backup)
GRAFANA_INI=/etc/grafana/grafana.ini
[ -f "$GRAFANA_INI.hmdm-stats.orig" ] || cp -p "$GRAFANA_INI" "$GRAFANA_INI.hmdm-stats.orig"
OVERRIDES=$(mktemp)
envsubst '${GRAFANA_BIND_ADDR}' <"$RUNTIME/grafana/grafana-overrides.ini.tmpl" >"$OVERRIDES"
# optional SMTP block, only when email alerting is configured
if [ -n "${ALERT_EMAIL_TO:-}" ]; then
    if [ -z "${SMTP_HOST:-}" ]; then
        echo "WARN: ALERT_EMAIL_TO set but SMTP_HOST empty — email notifications will not send" >&2
    else
        {
            echo "[smtp]"
            echo "enabled = true"
            echo "host = $SMTP_HOST"
            [ -n "${SMTP_USER:-}" ] && echo "user = $SMTP_USER"
            [ -n "${SMTP_PASSWORD:-}" ] && echo "password = $SMTP_PASSWORD"
            echo "from_address = ${SMTP_FROM:-grafana@localhost}"
        } >>"$OVERRIDES"
    fi
fi
python3 - "$GRAFANA_INI" "$OVERRIDES" <<'PYEOF'
import configparser, sys
target, overrides = sys.argv[1], sys.argv[2]
def load(path):
    cp = configparser.ConfigParser(interpolation=None, strict=False, allow_no_value=True)
    cp.read(path)
    return cp
base, over = load(target), load(overrides)
for section in over.sections():
    if not base.has_section(section):
        base.add_section(section)
    for key, value in over.items(section):
        base.set(section, key, value)
with open(target, "w") as fh:
    base.write(fh)
PYEOF
rm -f "$OVERRIDES"

# provisioning files
mkdir -p /etc/grafana/provisioning/{datasources,dashboards,alerting} "$GRAFANA_DASH_DIR"
envsubst '${HMDM_DB_NAME} ${HMDM_GRAFANA_RO_PASSWORD}' \
    <"$RUNTIME/grafana/provisioning/datasources/hmdm-postgres.yaml.tmpl" \
    >/etc/grafana/provisioning/datasources/hmdm-postgres.yaml
chown root:grafana /etc/grafana/provisioning/datasources/hmdm-postgres.yaml
chmod 640 /etc/grafana/provisioning/datasources/hmdm-postgres.yaml
install -m 644 "$RUNTIME/grafana/provisioning/dashboards/hmdm-stats.yaml" \
    /etc/grafana/provisioning/dashboards/hmdm-stats.yaml
install -m 644 "$RUNTIME/grafana/provisioning/dashboards/json/fleet-dashboard.json" \
    "$GRAFANA_DASH_DIR/fleet-dashboard.json"
chown -R grafana:grafana "$GRAFANA_DASH_DIR"

export BATTERY_WARN BATTERY_CRIT OFFLINE_ALERT_SECONDS ONLINE_THRESHOLD_SECONDS
envsubst '${BATTERY_WARN} ${BATTERY_CRIT} ${OFFLINE_ALERT_SECONDS} ${ONLINE_THRESHOLD_SECONDS}' \
    <"$RUNTIME/grafana/provisioning/alerting/rules.yaml.tmpl" \
    >/etc/grafana/provisioning/alerting/hmdm-rules.yaml
chmod 644 /etc/grafana/provisioning/alerting/hmdm-rules.yaml

# contact points: include only receivers that are configured
if [ -n "${ALERT_EMAIL_TO:-}" ] || [ -n "${ALERT_WEBHOOK_URL:-}" ]; then
    CP=/etc/grafana/provisioning/alerting/hmdm-contact-points.yaml
    {
        echo "apiVersion: 1"
        echo "contactPoints:"
        echo "  - orgId: 1"
        echo "    name: hmdm-alerts"
        echo "    receivers:"
        if [ -n "${ALERT_EMAIL_TO:-}" ]; then
            echo "      - uid: hmdm-alerts-email"
            echo "        type: email"
            echo "        settings:"
            echo "          addresses: \"$ALERT_EMAIL_TO\""
            echo "          singleEmail: true"
        fi
        if [ -n "${ALERT_WEBHOOK_URL:-}" ]; then
            echo "      - uid: hmdm-alerts-webhook"
            echo "        type: webhook"
            echo "        settings:"
            echo "          url: \"$ALERT_WEBHOOK_URL\""
            echo "          httpMethod: POST"
        fi
    } >"$CP"
    chmod 640 "$CP"; chown root:grafana "$CP"
    install -m 644 "$RUNTIME/grafana/provisioning/alerting/notification-policies.yaml.tmpl" \
        /etc/grafana/provisioning/alerting/hmdm-notification-policies.yaml
else
    echo "WARN: neither ALERT_EMAIL_TO nor ALERT_WEBHOOK_URL set — alert rules are" >&2
    echo "      provisioned but route to Grafana's default (empty) receiver." >&2
    rm -f /etc/grafana/provisioning/alerting/hmdm-contact-points.yaml \
          /etc/grafana/provisioning/alerting/hmdm-notification-policies.yaml
fi

say "start grafana"
systemctl daemon-reload
systemctl enable grafana-server >/dev/null
systemctl restart grafana-server
HEALTH_URL="http://$GRAFANA_BIND_ADDR:3000/api/health"
for i in $(seq 1 30); do
    if curl -fsS "$HEALTH_URL" >/dev/null 2>&1; then break; fi
    [ "$i" -eq 30 ] && {
        echo "Grafana did not become healthy at $HEALTH_URL." >&2
        echo "Restore config with: cp $GRAFANA_INI.hmdm-stats.orig $GRAFANA_INI && systemctl restart grafana-server" >&2
        exit 1
    }
    sleep 2
done
echo "grafana healthy at $HEALTH_URL"
# second restart: alert-rule provisioning needs the folder created by the
# dashboard provider on the first pass
systemctl restart grafana-server
sleep 3

# --- 8. web panel Analytics tab -------------------------------------------------------------
if [ "$SKIP_WEBPANEL" -eq 0 ]; then
    say "web panel Analytics tab"
    GRAFANA_URL="$GRAFANA_URL" WEBAPP_DIR="${WEBAPP_DIR:-}" \
        bash "$RUNTIME/webpanel/inject-analytics-tab.sh" || true
fi

# --- 9. done ----------------------------------------------------------------------------------
say "install complete"
cat <<EOF
Dashboard:   $GRAFANA_URL/d/hmdm-fleet  (LAN only — do not port-forward)
Snapshots:   every $SNAPSHOT_INTERVAL_MIN min as $CRON_USER (/etc/cron.d/hmdm-stats)
Logs:        $LOG_DIR/snapshot.log
Config:      $CONF
Verify:      sudo -u postgres psql -d $HMDM_DB_NAME -f $RUNTIME/sql/verify.sql
Acceptance checklist: see README.md section "Acceptance checklist".
EOF
